PasswordRestoreInput:
    type: input-object
    config:
        fields:
            token:
                type: "String!"
                description: "Password resetting token"
            password:
                type: "String!"
                description: "New password"